## Documentation
1. 50 stocks adju close data collected using data_collector file for 15 years
2. give input date and se all stocks daily,weekly,monthly,quartely,yearly and ytd performance

In [13]:
import numpy as np
import pandas as pd
import datetime as dt
from datetime import timedelta


pd.set_option('display.max_columns',None)

In [14]:
df = pd.read_csv('masterFile.csv')
df

,Date,Nifty,ADANIENT,ADANIPORTS,APOLLOHOSP,ASIANPAINT,AXISBANK,BAJAJ-AUTO,BAJAJFINSV,BAJFINANCE,BHARTIARTL,BPCL,BRITANNIA,CIPLA,COALINDIA,DIVISLAB,DRREDDY,EICHERMOT,GRASIM,HCLTECH,HDFC,HDFCBANK,HDFCLIFE,HEROMOTOCO,HINDALCO,HINDUNILVR,ICICIBANK,INDUSINDBK,INFY,ITC,JSWSTEEL,KOTAKBANK,LT,M&M,MARUTI,NESTLEIND,NTPC,ONGC,POWERGRID,RELIANCE,SBILIFE,SBIN,SUNPHARMA,TATACONSUM,TATAMOTORS,TATASTEEL,TCS,TECHM,TITAN,ULTRACEMCO,UPL,WIPRO
0,01-01-2008,6144.35,75.36,238.62,268.92,98.24,173.69,434.79,2557.11,37.54,416.41,47.42,115.66,194.84,NaN,409.91,640.47,33.30,506.10,56.74,470.37,154.27,NaN,425.57,170.72,161.33,182.25,115.69,155.22,50.28,102.04,318.87,751.52,189.19,884.45,437.20,123.42,110.08,69.14,632.42,NaN,186.27,107.71,71.09,130.94,27.21,194.16,222.26,70.24,926.83,99.16,99.77
1,02-01-2008,6179.40,79.13,240.57,269.40,98.44,184.78,434.05,2559.07,40.22,415.83,47.53,116.82,201.99,NaN,412.03,658.49,33.00,503.43,55.38,492.29,153.00,NaN,425.75,172.18,159.37,187.97,116.64,155.35,51.09,100.85,345.01,750.09,187.26,889.36,437.20,123.25,111.78,68.77,635.41,NaN,189.38,106.51,75.73,136.30,27.25,193.32,219.18,71.51,927.43,105.01,98.87
2,03-01-2008,6178.55,79.47,234.74,261.28,98.67,184.99,430.49,2532.60,39.11,408.45,49.46,118.62,199.68,NaN,410.94,630.89,34.78,484.35,54.62,490.07,151.14,NaN,432.60,168.70,164.58,182.28,114.84,151.86,49.55,103.81,332.79,734.95,181.94,868.09,437.20,132.36,115.00,71.60,644.73,NaN,187.18,102.12,74.31,135.96,27.03,186.15,220.86,70.12,922.06,105.51,95.94
3,04-01-2008,6274.30,79.23,228.22,260.99,98.83,188.39,432.95,2540.44,44.01,408.13,49.01,118.04,197.19,NaN,409.85,643.61,33.93,483.16,55.51,503.18,151.32,NaN,426.88,174.20,171.37,190.79,117.89,150.60,50.68,103.24,340.51,770.11,180.14,860.01,437.20,130.13,118.29,71.22,664.56,NaN,186.68,99.94,76.39,134.25,27.18,185.07,218.41,69.80,913.00,107.52,96.03
4,07-01-2008,6279.10,78.20,225.81,255.73,105.03,194.69,423.05,2485.54,42.76,403.26,47.46,119.48,196.27,NaN,409.39,629.12,33.88,472.90,52.73,501.54,147.66,NaN,427.73,172.70,175.17,202.10,117.22,145.45,53.45,100.48,342.70,776.30,177.97,859.66,437.20,128.86,114.40,70.63,670.61,NaN,187.78,100.87,75.06,134.90,27.02,179.62,211.67,75.96,923.42,108.32,93.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3786,15-06-2023,18688.10,2485.65,739.50,5218.75,3294.35,977.15,4721.55,1474.70,7126.60,829.70,378.90,4975.45,998.20,228.60,3581.05,4803.45,3534.70,1772.50,1143.60,2620.15,1582.05,576.25,2843.05,423.05,2667.91,926.60,1297.10,1286.80,448.10,770.60,1833.50,2361.30,1392.75,9594.85,22966.20,186.70,157.65,246.45,2552.55,1241.10,566.50,988.40,865.00,568.45,110.15,3216.30,1081.50,2908.00,8333.20,680.80,388.95
3787,16-06-2023,18826.00,2509.60,747.40,5200.05,3316.85,981.55,4641.95,1508.60,7203.20,837.80,376.80,5044.70,1006.05,228.55,3579.60,4915.05,3538.90,1780.75,1148.20,2650.45,1602.75,609.55,2832.05,426.95,2693.65,934.20,1314.00,1291.65,453.10,776.10,1857.40,2366.80,1403.85,9603.70,22968.55,188.20,157.00,246.45,2577.40,1281.35,571.25,992.00,862.75,569.80,110.64,3174.90,1077.20,2954.30,8333.25,690.85,381.30
3788,19-06-2023,18755.45,2401.40,735.65,5145.00,3309.70,965.65,4597.35,1541.95,7386.20,828.15,374.75,5021.05,1011.25,227.15,3584.75,4879.00,3496.65,1761.30,1137.55,2654.80,1604.15,626.55,2782.60,426.15,2683.25,923.15,1301.40,1294.00,453.60,771.65,1824.55,2366.35,1402.55,9532.00,22794.85,185.85,157.80,243.10,2551.80,1280.50,568.85,1001.80,857.00,566.05,110.49,3210.40,1093.60,2968.60,8268.60,685.60,380.15
3789,20-06-2023,18816.70,2414.80,737.80,5162.05,3318.70,974.85,4662.00,1521.05,7248.80,831.20,372.45,5056.45,1011.15,227.25,3566.20,4901.20,3562.10,1769.10,1168.65,2658.55,1607.50,643.70,2800.70,428.95,2676.10,925.55,1298.40,1303.40,452.85,773.15,1844.00,2382.00,1396.45,9492.10,22955.55,187.50,157.25,248.75,2557.10,1295.35,567.40,991.95,858.90,583.25,110.64,3227.70,1107.35,2974.00,8243.45,683.45,382.50
3790,21-06-2023,18856.85,2405.95,749.45,5118.75,3316.10,966.00,4650.15,1519.25,7206.15,839.00,372.80,5069.55,1008.90,228.45,3509.55,4910.40,3570.45,1777.90,1170.45,2702.00,1635.60,642.50,2823.55,420.95,2676.60,924.70,1286.60,1299.35,447.05,758.75,1845.55,2394.45,1374.25,9440.85,22891.60,187.50,160.20,258.20,2564.30,1294.95,566.35,991.90,860.15,581.40,110.30,3258.20,1119.90,2971.10,8241.55,686.10,385.50

In [15]:
df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y')

In [16]:
df.set_index('Date',inplace=True)

In [17]:
df

,Nifty,ADANIENT,ADANIPORTS,APOLLOHOSP,ASIANPAINT,AXISBANK,BAJAJ-AUTO,BAJAJFINSV,BAJFINANCE,BHARTIARTL,BPCL,BRITANNIA,CIPLA,COALINDIA,DIVISLAB,DRREDDY,EICHERMOT,GRASIM,HCLTECH,HDFC,HDFCBANK,HDFCLIFE,HEROMOTOCO,HINDALCO,HINDUNILVR,ICICIBANK,INDUSINDBK,INFY,ITC,JSWSTEEL,KOTAKBANK,LT,M&M,MARUTI,NESTLEIND,NTPC,ONGC,POWERGRID,RELIANCE,SBILIFE,SBIN,SUNPHARMA,TATACONSUM,TATAMOTORS,TATASTEEL,TCS,TECHM,TITAN,ULTRACEMCO,UPL,WIPRO
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2008-01-01,6144.35,75.36,238.62,268.92,98.24,173.69,434.79,2557.11,37.54,416.41,47.42,115.66,194.84,NaN,409.91,640.47,33.30,506.10,56.74,470.37,154.27,NaN,425.57,170.72,161.33,182.25,115.69,155.22,50.28,102.04,318.87,751.52,189.19,884.45,437.20,123.42,110.08,69.14,632.42,NaN,186.27,107.71,71.09,130.94,27.21,194.16,222.26,70.24,926.83,99.16,99.77
2008-01-02,6179.40,79.13,240.57,269.40,98.44,184.78,434.05,2559.07,40.22,415.83,47.53,116.82,201.99,NaN,412.03,658.49,33.00,503.43,55.38,492.29,153.00,NaN,425.75,172.18,159.37,187.97,116.64,155.35,51.09,100.85,345.01,750.09,187.26,889.36,437.20,123.25,111.78,68.77,635.41,NaN,189.38,106.51,75.73,136.30,27.25,193.32,219.18,71.51,927.43,105.01,98.87
2008-01-03,6178.55,79.47,234.74,261.28,98.67,184.99,430.49,2532.60,39.11,408.45,49.46,118.62,199.68,NaN,410.94,630.89,34.78,484.35,54.62,490.07,151.14,NaN,432.60,168.70,164.58,182.28,114.84,151.86,49.55,103.81,332.79,734.95,181.94,868.09,437.20,132.36,115.00,71.60,644.73,NaN,187.18,102.12,74.31,135.96,27.03,186.15,220.86,70.12,922.06,105.51,95.94
2008-01-04,6274.30,79.23,228.22,260.99,98.83,188.39,432.95,2540.44,44.01,408.13,49.01,118.04,197.19,NaN,409.85,643.61,33.93,483.16,55.51,503.18,151.32,NaN,426.88,174.20,171.37,190.79,117.89,150.60,50.68,103.24,340.51,770.11,180.14,860.01,437.20,130.13,118.29,71.22,664.56,NaN,186.68,99.94,76.39,134.25,27.18,185.07,218.41,69.80,913.00,107.52,96.03
2008-01-07,6279.10,78.20,225.81,255.73,105.03,194.69,423.05,2485.54,42.76,403.26,47.46,119.48,196.27,NaN,409.39,629.12,33.88,472.90,52.73,501.54,147.66,NaN,427.73,172.70,175.17,202.10,117.22,145.45,53.45,100.48,342.70,776.30,177.97,859.66,437.20,128.86,114.40,70.63,670.61,NaN,187.78,100.87,75.06,134.90,27.02,179.62,211.67,75.96,923.42,108.32,93.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-06-15,18688.10,2485.65,739.50,5218.75,3294.35,977.15,4721.55,1474.70,7126.60,829.70,378.90,4975.45,998.20,228.60,3581.05,4803.45,3534.70,1772.50,1143.60,2620.15,1582.05,576.25,2843.05,423.05,2667.91,926.60,1297.10,1286.80,448.10,770.60,1833.50,2361.30,1392.75,9594.85,22966.20,186.70,157.65,246.45,2552.55,1241.10,566.50,988.40,865.00,568.45,110.15,3216.30,1081.50,2908.00,8333.20,680.80,388.95
2023-06-16,18826.00,2509.60,747.40,5200.05,3316.85,981.55,4641.95,1508.60,7203.20,837.80,376.80,5044.70,1006.05,228.55,3579.60,4915.05,3538.90,1780.75,1148.20,2650.45,1602.75,609.55,2832.05,426.95,2693.65,934.20,1314.00,1291.65,453.10,776.10,1857.40,2366.80,1403.85,9603.70,22968.55,188.20,157.00,246.45,2577.40,1281.35,571.25,992.00,862.75,569.80,110.64,3174.90,1077.20,2954.30,8333.25,690.85,381.30
2023-06-19,18755.45,2401.40,735.65,5145.00,3309.70,965.65,4597.35,1541.95,7386.20,828.15,374.75,5021.05,1011.25,227.15,3584.75,4879.00,3496.65,1761.30,1137.55,2654.80,1604.15,626.55,2782.60,426.15,2683.25,923.15,1301.40,1294.00,453.60,771.65,1824.55,2366.35,1402.55,9532.00,22794.85,185.85,157.80,243.10,2551.80,1280.50,568.85,1001.80,857.00,566.05,110.49,3210.40,1093.60,2968.60,8268.60,685.60,380.15
2023-06-20,18816.70,2414.80,737.80,5162.05,3318.70,974.85,4662.00,1521.05,7248.80,831.20,372.45,5056.45,1011.15,227.25,3566.20,4901.20,3562.10,1769.10,1168.65,2658.55,1607.50,643.70,2800.70,428.95,2676.10,925.55,1298.40,1303.40,452.85,773.15,1844.00,2382.00,1396.45,9492.10,22955.55,187.50,157.25,248.75,2557.10,1295.35,567.40,991.95,858.90,583.25,110.64,3227.70,1107.35,2974.00,8243.45,683.45,382.50
2023-06-21,18856.85,2405.95,749.45,5118.75,3316.10,966.00,4650.15,1519.25,7206.15,839.00,372.80,5069.55,1008.90,228.45,3509.55,4910.40,3570.45,1777.90,1170.45,2702.00,1635.60,642.50,2823.55,420.95,2676.60,924.70,1286.60,1299.35,447.05,758.75,1845.55,2394.45,1374.25,9440.85,22891.60,187.50,160.20,258.20,2564.30,1294.95,566.35,991.90,860.15,581.40,110.30,3258.20,1119.90,2971.10,8241.55,686.10,385.50

## making empty dataframe first

In [19]:
companyLiist = df.columns.to_list()

index_columns = companyLiist
empty_columns = ['daily', 'weekly', 'monthly', 'quarterly', 'yearly', 'ytd', 'custom']

main_df = pd.DataFrame(index=index_columns, columns=empty_columns)
main_df

           daily weekly monthly quarterly yearly  ytd custom
Nifty        NaN    NaN     NaN       NaN    NaN  NaN    NaN
ADANIENT     NaN    NaN     NaN       NaN    NaN  NaN    NaN
ADANIPORTS   NaN    NaN     NaN       NaN    NaN  NaN    NaN
APOLLOHOSP   NaN    NaN     NaN       NaN    NaN  NaN    NaN
ASIANPAINT   NaN    NaN     NaN       NaN    NaN  NaN    NaN
AXISBANK     NaN    NaN     NaN       NaN    NaN  NaN    NaN
BAJAJ-AUTO   NaN    NaN     NaN       NaN    NaN  NaN    NaN
BAJAJFINSV   NaN    NaN     NaN       NaN    NaN  NaN    NaN
BAJFINANCE   NaN    NaN     NaN       NaN    NaN  NaN    NaN
BHARTIARTL   NaN    NaN     NaN       NaN    NaN  NaN    NaN
BPCL         NaN    NaN     NaN       NaN    NaN  NaN    NaN
BRITANNIA    NaN    NaN     NaN       NaN    NaN  NaN    NaN
CIPLA        NaN    NaN     NaN       NaN    NaN  NaN    NaN
COALINDIA    NaN    NaN     NaN       NaN    NaN  NaN    NaN
DIVISLAB     NaN    NaN     NaN       NaN    NaN  NaN    NaN
DRREDDY      NaN    NaN     NaN       NaN    NaN  NaN    NaN
EICHERMOT    NaN    NaN     NaN       NaN    NaN  NaN    NaN
GRASIM       NaN    NaN     NaN       NaN    NaN  NaN    NaN
HCLTECH      NaN    NaN     NaN       NaN    NaN  NaN    NaN
HDFC         NaN    NaN     NaN       NaN    NaN  NaN    NaN
HDFCBANK     NaN    NaN     NaN       NaN    NaN  NaN    NaN
HDFCLIFE     NaN    NaN     NaN       NaN    NaN  NaN    NaN
HEROMOTOCO   NaN    NaN     NaN       NaN    NaN  NaN    NaN
HINDALCO     NaN    NaN     NaN       NaN    NaN  NaN    NaN
HINDUNILVR   NaN    NaN     NaN       NaN    NaN  NaN    NaN
ICICIBANK    NaN    NaN     NaN       NaN    NaN  NaN    NaN
INDUSINDBK   NaN    NaN     NaN       NaN    NaN  NaN    NaN
INFY         NaN    NaN     NaN       NaN    NaN  NaN    NaN
ITC          NaN    NaN     NaN       NaN    NaN  NaN    NaN
JSWSTEEL     NaN    NaN     NaN       NaN    NaN  NaN    NaN
KOTAKBANK    NaN    NaN     NaN       NaN    NaN  NaN    NaN
LT           NaN    NaN     NaN       NaN    NaN  NaN    NaN
M&M          NaN    NaN     NaN       NaN    NaN  NaN    NaN
MARUTI       NaN    NaN     NaN       NaN    NaN  NaN    NaN
NESTLEIND    NaN    NaN     NaN       NaN    NaN  NaN    NaN
NTPC         NaN    NaN     NaN       NaN    NaN  NaN    NaN
ONGC         NaN    NaN     NaN       NaN    NaN  NaN    NaN
POWERGRID    NaN    NaN     NaN       NaN    NaN  NaN    NaN
RELIANCE     NaN    NaN     NaN       NaN    NaN  NaN    NaN
SBILIFE      NaN    NaN     NaN       NaN    NaN  NaN    NaN
SBIN         NaN    NaN     NaN       NaN    NaN  NaN    NaN
SUNPHARMA    NaN    NaN     NaN       NaN    NaN  NaN    NaN
TATACONSUM   NaN    NaN     NaN       NaN    NaN  NaN    NaN
TATAMOTORS   NaN    NaN     NaN       NaN    NaN  NaN    NaN
TATASTEEL    NaN    NaN     NaN       NaN    NaN  NaN    NaN
TCS          NaN    NaN     NaN       NaN    NaN  NaN    NaN
TECHM        NaN    NaN     NaN       NaN    NaN  NaN    NaN
TITAN        NaN    NaN     NaN       NaN    NaN  NaN    NaN
ULTRACEMCO   NaN    NaN     NaN       NaN    NaN  NaN    NaN
UPL          NaN    NaN     NaN       NaN    NaN  NaN    NaN
WIPRO        NaN    NaN     NaN       NaN    NaN  NaN    NaN

## input date

In [20]:
inputDate = "2021-08-12"
inputDateDt = pd.to_datetime(inputDate)

In [21]:
#optional 
fromDate = '2021-08-11'
fromDateDt = pd.to_datetime(fromDate)

In [22]:
# dates setup for ytd
year = inputDateDt.year
prevYear = year-1
print(year)
print(prevYear)

dateString = f"31-march-{year}"
print(dateString)
dateString2 = f"31-march-{prevYear}"
print(dateString2)


x = pd.to_datetime(dateString)
print(x)

y = pd.to_datetime(dateString2)
print(y)

2021
2020
31-march-2021
31-march-2020
2021-03-31 00:00:00
2020-03-31 00:00:00

In [23]:
if inputDateDt in df.index:
    currentPriceList = df.loc[inputDateDt]
else:
    print(f'{inputDateDt} not present in data take another date as current date')

# 1 day before     (daily)
dailyBaseDate =  inputDateDt - timedelta(days=1)

#   7 days before v (weekly)
weeklyBaseDate = inputDateDt - timedelta(days=7)

# 30 days before  (monthly)
monthlyBaseDate = inputDateDt - timedelta(days=30)


#90 days before (quarterly)
quarterlyBaseDate = inputDateDt - timedelta(days=90)

# 365 days before (yearly)
yearlyBaseDate = inputDateDt - timedelta(days=365)

#ytd 
if inputDateDt>x:
    ytdBaseDate = x

else:
    ytdBaseDate = y


#FROM PARTICULAR BASE DATE
customBaseDate = fromDateDt


## daily
if dailyBaseDate >= df.index[0] and dailyBaseDate <= df.index[-1]:  #if base date in range
    if dailyBaseDate in df.index:                                             #if base date present directly
        basePriceList  = df.loc[dailyBaseDate]
        dailyReturnPer =  round(((currentPriceList/basePriceList -1)*100),1).values
        main_df.loc[:,'daily'] = dailyReturnPer


    else:
        temp_df = df[df.index < dailyBaseDate]  
        nearest_index = temp_df.index.searchsorted(inputDateDt)-1      #will get index
        date = temp_df.index[nearest_index]                                         #will get date 
        basePriceList = temp_df.loc[date]                                           #will get row or values
        dailyReturnPer =  round(((currentPriceList/basePriceList -1)*100),1).values
        main_df.loc[:,'daily'] = dailyReturnPer
else:
    print('Date is out of range of dates')


## weekly
if weeklyBaseDate >= df.index[0] and weeklyBaseDate <= df.index[-1]:  #if base date in range
    if weeklyBaseDate in df.index:                                             #if base date present directly
        basePriceList  = df.loc[weeklyBaseDate]
        weeklyReturnPer =  round(((currentPriceList/basePriceList -1)*100),1).values
        main_df.loc[:,'weekly'] = weeklyReturnPer


    else:
        temp_df = df[df.index < weeklyBaseDate]  
        nearest_index = temp_df.index.searchsorted(inputDateDt)-1      #will get index
        date = temp_df.index[nearest_index]                                         #will get date 
        basePriceList = temp_df.loc[date]                                           #will get row or values
        weeklyReturnPer =  round(((currentPriceList/basePriceList -1)*100),1).values
        main_df.loc[:,'weekly'] = weeklyReturnPer
else:
    print('Date is out of range of dates')



## monthly
if monthlyBaseDate >= df.index[0] and monthlyBaseDate <= df.index[-1]:  #if base date in range
    if monthlyBaseDate in df.index:                                             #if base date present directly
        basePriceList  = df.loc[monthlyBaseDate]
        monthlyReturnPer =  round(((currentPriceList/basePriceList -1)*100),1).values
        main_df.loc[:,'monthly'] = monthlyReturnPer


    else:
        temp_df = df[df.index < monthlyBaseDate]  
        nearest_index = temp_df.index.searchsorted(inputDateDt)-1      #will get index
        date = temp_df.index[nearest_index]                                         #will get date 
        basePriceList = temp_df.loc[date]                                           #will get row or values
        monthlyReturnPer =  round(((currentPriceList/basePriceList -1)*100),1).values
        main_df.loc[:,'monthly'] = monthlyReturnPer
else:
    print('Date is out of range of dates')



## quarterly
if quarterlyBaseDate >= df.index[0] and quarterlyBaseDate <= df.index[-1]:  #if base date in range
    if quarterlyBaseDate in df.index:                                             #if base date present directly
        basePriceList  = df.loc[quarterlyBaseDate]
        quarterlyReturnPer =  round(((currentPriceList/basePriceList -1)*100),1).values
        main_df.loc[:,'quarterly'] = quarterlyReturnPer


    else:
        temp_df = df[df.index < quarterlyBaseDate]  
        nearest_index = temp_df.index.searchsorted(inputDateDt)-1      #will get index
        date = temp_df.index[nearest_index]                                         #will get date 
        basePriceList = temp_df.loc[date]                                           #will get row or values
        quarterlyReturnPer =  round(((currentPriceList/basePriceList -1)*100),1).values
        main_df.loc[:,'quarterly'] = quarterlyReturnPer
else:
    print('Date is out of range of dates')



## yearly
if yearlyBaseDate >= df.index[0] and yearlyBaseDate <= df.index[-1]:  #if base date in range
    if yearlyBaseDate in df.index:                                             #if base date present directly
        basePriceList  = df.loc[yearlyBaseDate]
        yearlyReturnPer =  round(((currentPriceList/basePriceList -1)*100),1).values
        main_df.loc[:,'yearly'] = yearlyReturnPer


    else:
        temp_df = df[df.index < yearlyBaseDate]  
        nearest_index = temp_df.index.searchsorted(inputDateDt)-1      #will get index
        date = temp_df.index[nearest_index]                                         #will get date 
        basePriceList = temp_df.loc[date]                                           #will get row or values
        yearlyReturnPer =  round(((currentPriceList/basePriceList -1),1)*100).values
        main_df.loc[:,'yearly'] = yearlyReturnPer
else:
    print('Date is out of range of dates')



## ytd
if ytdBaseDate >= df.index[0] and ytdBaseDate <= df.index[-1]:  #if base date in range
    if ytdBaseDate in df.index:                                             #if base date present directly
        basePriceList  = df.loc[ytdBaseDate]
        ytdReturnPer =  round(((currentPriceList/basePriceList -1)*100),1).values
        main_df.loc[:,'ytd'] = ytdReturnPer


    else:
        temp_df = df[df.index < ytdBaseDate]  
        nearest_index = temp_df.index.searchsorted(inputDateDt)-1      #will get index
        date = temp_df.index[nearest_index]                                         #will get date 
        basePriceList = temp_df.loc[date]                                           #will get row or values
        ytdReturnPer =  round(((currentPriceList/basePriceList -1)*100),1).values
        main_df.loc[:,'ytd'] = yearlyReturnPer
else:
    print('Date is out of range of dates')


#custom from date
if customBaseDate >= df.index[0] and customBaseDate <= df.index[-1]:  #if base date in range
    if customBaseDate in df.index:                                             #if base date present directly
        basePriceList  = df.loc[customBaseDate]
        customReturnPer =  round(((currentPriceList/basePriceList -1)*100),1).values
        main_df.loc[:,'custom'] = customReturnPer


    else:
        temp_df = df[df.index < customBaseDate]  
        nearest_index = temp_df.index.searchsorted(inputDateDt)-1      #will get index
        date = temp_df.index[nearest_index]                                         #will get date 
        basePriceList = temp_df.loc[date]                                           #will get row or values
        customReturnPer =  round(((currentPriceList/basePriceList -1)*100),1).values
        main_df.loc[:,'custom'] = yearlyReturnPer
else:
    print('Date is out of range of dates')


main_df

C:\Users\Admin\AppData\Local\Temp\ipykernel_2696\230947065.py:39: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  main_df.loc[:,'daily'] = dailyReturnPer
C:\Users\Admin\AppData\Local\Temp\ipykernel_2696\230947065.py:58: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  main_df.loc[:,'weekly'] = weeklyReturnPer
C:\Users\Admin\AppData\Local\Temp\ipykernel_2696\230947065.py:78: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  main_df.loc[:,'monthly'] = monthlyReturnPer
C:\Users\Admin\AppData\Local\Temp\ipykernel_2696\230947065.py:98: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  main_df.loc[:,'quarterly'] = quarterlyReturnPer
C:\Users\Admin\AppData\Local\Temp\ipykernel_2696\230947065.py:118: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  main_df.loc[:,'yearly'] = yearlyReturnPer
C:\Users\Admin\AppData\Local\Temp\ipykernel_2696\230947065.py:138: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  main_df.loc[:,'ytd'] = ytdReturnPer
C:\Users\Admin\AppData\Local\Temp\ipykernel_2696\230947065.py:157: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  main_df.loc[:,'custom'] = customReturnPer

            daily  weekly  monthly  quarterly  yearly   ytd  custom
Nifty         0.5     0.4      3.5       11.5    44.7  11.4     0.5
ADANIENT      0.4     0.7      1.8       18.3   630.3  40.0     0.4
ADANIPORTS    0.7     1.5      0.0       -3.3   107.8   0.9     0.7
APOLLOHOSP    2.7     1.5     10.2       31.6   142.5  42.4     2.7
ASIANPAINT    0.1    -0.4     -0.6        7.8    66.6  17.8     0.1
AXISBANK     -0.4     1.1     -1.7       10.6    67.9   8.6    -0.4
BAJAJ-AUTO    1.1    -1.3     -5.0        1.3    29.0   6.2     1.1
BAJAJFINSV    1.0     2.5     11.1       30.7   125.7  48.4     1.0
BAJFINANCE    0.5    -0.8      0.7       16.5    81.7  20.6     0.5
BHARTIARTL    0.4     4.1     17.6       11.2    13.8  20.5     0.4
BPCL         -0.4    -1.2     -0.5        1.3    11.8   4.7    -0.4
BRITANNIA    -0.1     0.3      3.9        3.8    -0.9   1.9    -0.1
CIPLA        -0.5    -3.7     -5.7        0.7    19.5  11.7    -0.5
COALINDIA     0.3    -0.8     -2.5       -1.7    23.3  10.7     0.3
DIVISLAB     -0.2    -0.3      6.6       22.1    57.5  35.5    -0.2
DRREDDY      -0.6    -1.4    -13.3       -8.4     5.4   5.4    -0.6
EICHERMOT    -3.7    -3.6     -2.7        9.0    19.0   1.1    -3.7
GRASIM       -0.4    -2.7     -5.1        9.5   140.4   3.2    -0.4
HCLTECH       2.8     3.3     14.0       21.2    57.3  13.5     2.8
HDFC          0.4     0.3      4.9       11.2    48.4   7.8     0.4
HDFCBANK      0.4     1.1     -0.0        8.7    41.8   1.0     0.4
HDFCLIFE      1.2     0.8     -2.7        0.9    11.2  -2.8     1.2
HEROMOTOCO    0.0    -1.3     -3.8       -0.7     0.8  -4.1     0.0
HINDALCO      0.8    -0.6     12.3       15.0   151.8  34.7     0.8
HINDUNILVR    0.1     1.5     -1.8        1.4    10.5  -0.9     0.1
ICICIBANK     1.1    -0.2      5.8       17.8    91.7  20.9     1.1
INDUSINDBK   -0.6     3.8     -1.9       16.2    98.8   8.5    -0.6
INFY          0.7     2.2      9.4       29.7    80.8  24.8     0.7
ITC           0.1    -2.9      3.5        1.1     7.6  -1.7     0.1
JSWSTEEL     -0.0    -1.9      6.8        8.0   197.4  63.0    -0.0
KOTAKBANK     0.4     0.9      2.4        4.8    34.0   2.0     0.4
LT            2.5    -0.2      8.5       16.0    76.2  15.7     2.5
M&M          -0.3     2.2      0.5        5.9    23.6  -1.3    -0.3
MARUTI       -0.1    -0.2     -5.0        4.8     5.8   2.9    -0.1
NESTLEIND    -0.2    -0.4      2.5        5.3    11.1   6.2    -0.2
NTPC          1.9     2.3     -0.6        7.0    47.1  11.9     1.9
ONGC         -0.6    -0.5     -3.4        2.9    51.4  13.8    -0.6
POWERGRID     6.1     6.7      9.0        9.0    49.7  15.6     6.1
RELIANCE     -0.3    -1.1      0.5        9.3    -0.5   5.7    -0.3
SBILIFE      -0.1    -0.1      7.7       15.9    32.7  29.1    -0.1
SBIN         -0.2    -3.3     -0.4       19.6   112.0  18.4    -0.2
SUNPHARMA    -0.1    -0.9     14.0       12.6    47.9  30.3    -0.1
TATACONSUM    1.2     0.8      0.2       20.7    50.5  21.9     1.2
TATAMOTORS    3.6     2.1     -1.6       -2.0   144.0   1.4     3.6
TATASTEEL     0.7    -0.8     16.8       29.6   255.2  80.7     0.7
TCS           0.2     2.1      5.4       10.6    50.5   6.2     0.2
TECHM         4.8    11.1     35.6       49.5   109.7  43.6     4.8
TITAN         1.9     1.3      6.0       25.6    73.1  17.3     1.9
ULTRACEMCO    0.2    -2.5      5.3       17.9    87.6  11.4     0.2
UPL           0.4    -0.0     -5.5        5.8    63.4  22.5     0.4
WIPRO         0.8     0.8     15.4       21.6   119.8  46.3     0.8

In [25]:
# main_df.to_excel('mainFile.xlsx')